# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BEC
version: "0.1.0"
slug: bec
description: BEC (Bryant Evolution Connex) add-on
url: "https://github.com/brunokc/ha-bec/tree/main/bec"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
ports:
  8080/tcp: 8080
#image: "ghcr.io/home-assistant/{arch}-addon-example"
