# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BEC
version: "0.1.0"
slug: bec
description: BEC (Bryant Evolution Connex) add-on for Home Assistant
url: "https://github.com/brunokc/ha-bec-addon"
codenotary: brunokc@kraychete.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
init: false
map:
  - share:rw
host_network: true
ports:
  8080/tcp: 8080
  8787/tcp: 8787
ports_description:
  8080/tcp: Port used to proxy communications between local devices and the cloud service
  8787/tcp: Port used for communication between the integration and the add-on
image: "ghcr.io/brunokc/{arch}-ha-bec-addon"
stage: experimental
